import "server-only";
import { randomUUID } from "crypto";
import { db } from "@/lib/db";
import { allocateNumber } from "@/server/number-series";
import { assertTenant, requireTenantProject } from "@/lib/tenant";
import { canTransitionAsset, canTransitionWorkOrder, straightLineBookValue } from "@/lib/assets";

async function activity(tenantId:string,actorId:string,assetId:string,eventType:string,summary:string,previousStatus?:string,nextStatus?:string,metadata?:unknown){return db.assetActivity.create({data:{tenantId,actorId,assetId,eventType,summary,previousStatus,nextStatus,correlationId:randomUUID(),metadata:metadata?JSON.stringify(metadata):undefined}})}
export async function getAssetsDashboard(tenantId:string){const now=new Date(),soon=new Date(now.getTime()+30*86400000);const[assets,orders,inspections,calibrations,warranties,insurance,activityRows]=await Promise.all([db.asset.findMany({where:{tenantId,archivedAt:null},include:{project:true,category:true},orderBy:{updatedAt:"desc"}}),db.assetWorkOrder.findMany({where:{tenantId,status:{notIn:["CLOSED","ARCHIVED"]}},include:{asset:true},orderBy:{slaDueAt:"asc"}}),db.assetInspection.findMany({where:{tenantId,result:{in:["PENDING","FAILED"]}},include:{asset:true},orderBy:{nextDueAt:"asc"}}),db.assetCalibration.findMany({where:{tenantId,nextDueAt:{lte:soon}},include:{asset:true},orderBy:{nextDueAt:"asc"}}),db.assetWarranty.findMany({where:{tenantId,expiresAt:{lte:soon},status:"ACTIVE"}}),db.assetInsurancePolicy.findMany({where:{tenantId,expiresAt:{lte:soon},status:"ACTIVE"}}),db.assetActivity.findMany({where:{tenantId},include:{asset:true},orderBy:{createdAt:"desc"},take:10})]);const acquisition=assets.reduce((s,a)=>s+(a.purchaseValue??0),0),book=assets.reduce((s,a)=>s+(a.bookValue??a.purchaseValue??0),0);return{assets,orders,inspections,calibrations,warranties,insurance,activity:activityRows,acquisitionValue:acquisition,bookValue:book,maintenanceCost:orders.reduce((s,o)=>s+o.laborCost+o.materialCost,0),downtimeHours:orders.reduce((s,o)=>s+o.downtimeHours,0)}}
export const listAssetsModule=(tenantId:string)=>db.asset.findMany({where:{tenantId,archivedAt:null},include:{project:true,category:true,_count:{select:{workOrders:true,inspections:true,assignments:true,documents:true}}},orderBy:{createdAt:"desc"}});
export async function getAsset(tenantId:string,id:string){return assertTenant(await db.asset.findUnique({where:{id},include:{project:true,category:true,assignments:{orderBy:{assignedAt:"desc"}},locations:{orderBy:{effectiveAt:"desc"}},maintenances:{orderBy:{nextDueAt:"asc"}},workOrders:{orderBy:{createdAt:"desc"}},inspections:{orderBy:{createdAt:"desc"}},calibrations:{orderBy:{nextDueAt:"asc"}},warranties:{orderBy:{expiresAt:"asc"}},insurancePolicies:{orderBy:{expiresAt:"asc"}},reservations:{orderBy:{startsAt:"desc"}},transfers:{orderBy:{transferredAt:"desc"}},documents:{orderBy:{createdAt:"desc"}},activities:{orderBy:{createdAt:"desc"}}}}),tenantId,"Asset")}
export const listAssetCategories=(tenantId:string)=>db.assetCategory.findMany({where:{tenantId},include:{_count:{select:{assets:true}},parent:true},orderBy:{name:"asc"}});
export const listAssetWorkOrders=(tenantId:string)=>db.assetWorkOrder.findMany({where:{tenantId},include:{asset:true,maintenance:true},orderBy:[{priority:"desc"},{createdAt:"desc"}]});
export const listAssetCompliance=async(tenantId:string)=>({inspections:await db.assetInspection.findMany({where:{tenantId},include:{asset:true},orderBy:{nextDueAt:"asc"}}),calibrations:await db.assetCalibration.findMany({where:{tenantId},include:{asset:true},orderBy:{nextDueAt:"asc"}}),warranties:await db.assetWarranty.findMany({where:{tenantId},include:{asset:true},orderBy:{expiresAt:"asc"}}),insurance:await db.assetInsurancePolicy.findMany({where:{tenantId},include:{asset:true},orderBy:{expiresAt:"asc"}})});

export async function createAsset(tenantId:string,actorId:string,input:{projectId?:string;categoryId?:string;name:string;type:string;ownershipCompanyId?:string;ownershipCompanyName?:string;manufacturer?:string;model?:string;serialNumber?:string;purchaseDate?:Date;purchaseValue?:number;currency:string;usefulLifeMonths?:number;salvageValue?:number;currentLocation?:string;notes?:string}){if(input.projectId)await requireTenantProject(tenantId,input.projectId);if(input.categoryId){const category=await db.assetCategory.findUnique({where:{id:input.categoryId},select:{tenantId:true}});assertTenant(category,tenantId,"AssetCategory")}const code=await allocateNumber(tenantId,"ASSET");const bookValue=input.purchaseValue&&input.purchaseDate&&input.usefulLifeMonths?straightLineBookValue(input.purchaseValue,input.salvageValue??0,input.usefulLifeMonths,input.purchaseDate):input.purchaseValue;const row=await db.asset.create({data:{tenantId,createdById:actorId,code,qrCode:code,barcode:code,...input,bookValue,status:"DRAFT"}});await activity(tenantId,actorId,row.id,"asset.created",`${code} ${row.name} created.`);return row}
// Asset.recordVersion existed from the start but nothing ever read it: every
// status writer below incremented it and then wrote with a bare `update`, so
// two concurrent callers could both read ACTIVE, both pass canTransitionAsset,
// and both write — last one wins, and the losing transition is still logged to
// AssetActivity as though it happened. These three compare-and-swap on
// (recordVersion, status) instead, the same guard units.ts uses on Unit.version.
// assignAsset/transferAsset moved to an interactive transaction so a lost race
// rolls back the assignment/transfer row it would otherwise leave behind.
export async function transitionAsset(tenantId:string,actorId:string,id:string,status:string){const row=assertTenant(await db.asset.findUnique({where:{id}}),tenantId,"Asset");if(!canTransitionAsset(row.status,status))throw new Error(`Cannot move ${row.status} to ${status}.`);const moved=await db.asset.updateMany({where:{id,recordVersion:row.recordVersion,status:row.status},data:{status,archivedAt:status==="ARCHIVED"?new Date():undefined,recordVersion:{increment:1}}});if(moved.count===0)throw new Error("This asset was changed by someone else. Reload and try again.");await activity(tenantId,actorId,id,"asset.status_changed",`${row.code??row.name} moved to ${status}.`,row.status,status)}
export async function assignAsset(tenantId:string,actorId:string,id:string,input:{assigneeType:string;assigneeId?:string;assigneeName:string;projectId?:string;location?:string;conditionOut?:string;notes?:string}){const row=assertTenant(await db.asset.findUnique({where:{id},include:{assignments:{where:{returnedAt:null}}}}),tenantId,"Asset");if(row.status==="MAINTENANCE"||row.status==="OUT_OF_SERVICE")throw new Error("This asset is not available for assignment.");if(input.projectId)await requireTenantProject(tenantId,input.projectId);await db.$transaction(async(tx)=>{await tx.assetAssignment.updateMany({where:{assetId:id,returnedAt:null},data:{returnedAt:new Date()}});await tx.assetAssignment.create({data:{tenantId,assetId:id,createdById:actorId,assignedAt:new Date(),...input}});const claimed=await tx.asset.updateMany({where:{id,recordVersion:row.recordVersion,status:row.status},data:{status:"ASSIGNED",projectId:input.projectId,currentLocation:input.location,custodianId:input.assigneeId,recordVersion:{increment:1}}});if(claimed.count===0)throw new Error("This asset was changed by someone else. Reload and try again.");});await activity(tenantId,actorId,id,"asset.assigned",`${row.code??row.name} assigned to ${input.assigneeName}.`,row.status,"ASSIGNED")}

// Phase 20 — transferAsset() used to write an AssetTransfer row and nothing
// else, so the asset itself never moved: the register, the detail page and
// every report still showed the old owner/project/location while the transfer
// log said otherwise. assignAsset() directly above does update the asset; this
// is the same fact recorded two ways, and only one of them was applied.
//
// The toType values are the six the transfer form actually offers (see
// TransferAssetDialog) — COMPANY, DEPARTMENT, TEAM, USER, PROJECT, WAREHOUSE.
// PROJECT and USER need a real id, which the form now collects; the rest carry
// their meaning in the free-text toName.
//
// TEAM maps to nothing on purpose: Asset has no team column, so the transfer is
// recorded in history and the asset row is left alone rather than having a team
// name written into some unrelated field.
function assetFieldsForTransfer(input:{toType:string;toId?:string;toName:string}){
  switch(input.toType){
    case "COMPANY": return {ownershipCompanyName:input.toName,...(input.toId?{ownershipCompanyId:input.toId}:{})};
    case "DEPARTMENT": return {department:input.toName};
    case "PROJECT": return input.toId?{projectId:input.toId}:{};
    case "USER": return input.toId?{custodianId:input.toId,status:"ASSIGNED"}:{};
    case "WAREHOUSE": return {currentLocation:input.toName};
    default: return {};
  }
}
export async function transferAsset(tenantId:string,actorId:string,id:string,input:{fromType:string;fromId?:string;fromName:string;toType:string;toId?:string;toName:string;transferredAt:Date;condition?:string;reason:string}){const row=assertTenant(await db.asset.findUnique({where:{id}}),tenantId,"Asset");if(["DISPOSED","ARCHIVED"].includes(row.status))throw new Error("Disposed or archived assets cannot be transferred.");const number=await allocateNumber(tenantId,"ASSET_TRANSFER");const assetUpdate=assetFieldsForTransfer(input);const transfer=await db.$transaction(async(tx)=>{const created=await tx.assetTransfer.create({data:{tenantId,assetId:id,createdById:actorId,number,...input}});const moved=await tx.asset.updateMany({where:{id,recordVersion:row.recordVersion,status:row.status},data:{...assetUpdate,recordVersion:{increment:1}}});if(moved.count===0)throw new Error("This asset was changed by someone else. Reload and try again.");return created});await activity(tenantId,actorId,id,"asset.transferred",`${number}: ${input.fromName} to ${input.toName}.`,undefined,undefined,input);return transfer}
export async function createWorkOrder(tenantId:string,actorId:string,input:{assetId:string;maintenanceId?:string;title:string;description?:string;priority:string;slaDueAt?:Date;scheduledStart?:Date;technicianName?:string}){const asset=assertTenant(await db.asset.findUnique({where:{id:input.assetId}}),tenantId,"Asset");const number=await allocateNumber(tenantId,"ASSET_WORK_ORDER");const row=await db.assetWorkOrder.create({data:{tenantId,createdById:actorId,number,...input}});await activity(tenantId,actorId,asset.id,"work_order.created",`${number} ${row.title} created.`);return row}
export async function transitionWorkOrder(tenantId:string,actorId:string,id:string,status:string){const row=await db.assetWorkOrder.findUnique({where:{id},include:{asset:true}});assertTenant(row,tenantId,"AssetWorkOrder");if(!canTransitionWorkOrder(row!.status,status))throw new Error(`Cannot move ${row!.status} to ${status}.`);await db.$transaction([db.assetWorkOrder.update({where:{id},data:{status,startedAt:status==="IN_PROGRESS"?new Date():undefined,completedAt:status==="COMPLETED"?new Date():undefined,closedAt:status==="CLOSED"?new Date():undefined}}),...(["IN_PROGRESS","WAITING_PARTS","WAITING_APPROVAL"].includes(status)?[db.asset.update({where:{id:row!.assetId},data:{status:"MAINTENANCE"}})]:status==="COMPLETED"?[db.asset.update({where:{id:row!.assetId},data:{status:"ACTIVE"}})]:[])]);await activity(tenantId,actorId,row!.assetId,"work_order.status_changed",`${row!.number} moved to ${status}.`,row!.status,status)}
