import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, CalendarDays, CheckCircle2, CircleDollarSign } from "lucide-react";
import { getCurrentUser } from "@/lib/dal";
import { can } from "@/lib/permissions";
import { getRfq, listProcurementActivity } from "@/server/procurement";
import { ProcurementNav } from "@/components/procurement/procurement-nav";
import { ProcurementStatusControl } from "@/components/procurement/procurement-status-control";
import { CreateQuotationDialog } from "@/components/procurement/procurement-dialogs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TBody, TD, TH, THead, TRow } from "@/components/ui/table";
import { formatCurrency, formatDate } from "@/lib/utils";
import { getConfigResolver } from "@/server/platform-config";

export default async function RfqPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { tenantId, role, company } = await getCurrentUser();
  if (!can(role, "PROCUREMENT", "READ")) redirect("/dashboard/executive");
  if (!(await getConfigResolver(tenantId, company?.id))("procurement.page.sourcing")) redirect("/dashboard/procurement");
  const [rfq, activity] = await Promise.all([getRfq(tenantId, id), listProcurementActivity(tenantId, "RFQ", id)]);
  const canWrite = can(role, "PROCUREMENT", "WRITE");
  const invited = rfq.suppliers.map((entry) => ({ id: entry.supplier.id, name: entry.supplier.name }));
  const lowest = rfq.quotations.length ? Math.min(...rfq.quotations.map((q) => q.total)) : null;
  return <div className="space-y-6"><Link href="/dashboard/procurement/sourcing" className="inline-flex items-center gap-1.5 text-sm text-ink-muted"><ArrowLeft size={14} /> RFQs and sourcing</Link><div className="flex flex-col gap-4 rounded-2xl border border-border bg-surface p-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-gold">{rfq.number}</span><Badge status={rfq.status}>{rfq.status.replaceAll("_", " ")}</Badge></div><h1 className="mt-2 text-2xl font-semibold text-ink">{rfq.title}</h1><p className="mt-2 max-w-3xl text-sm text-ink-muted">{rfq.instructions ?? "No special sourcing instructions."}</p><div className="mt-4 flex flex-wrap gap-4 text-xs text-ink-muted"><span>{rfq.project?.name ?? "Company-wide"}</span>{rfq.deadline && <span className="inline-flex items-center gap-1"><CalendarDays size={12} />Responses due {formatDate(rfq.deadline)}</span>}<span>Revision {rfq.version}</span></div></div><div className="flex gap-2">{canWrite && <CreateQuotationDialog rfqId={rfq.id} projectId={rfq.projectId} suppliers={invited} defaultDescription={rfq.lines[0]?.description} />}{canWrite && <ProcurementStatusControl entity="rfq" id={rfq.id} status={rfq.status} />}</div></div><ProcurementNav active="sourcing" />
    <div className="grid gap-4 lg:grid-cols-[1.2fr_2fr]"><Card><CardHeader><CardTitle>Requested scope</CardTitle></CardHeader><CardContent className="space-y-3">{rfq.lines.map((line) => <div key={line.id} className="rounded-lg bg-surface-sunken p-3"><p className="text-sm font-medium text-ink">{line.lineNumber}. {line.description}</p><p className="mt-1 text-xs text-ink-muted">{line.quantity} {line.unit}</p></div>)}<div className="border-t border-border pt-3"><p className="text-xs font-semibold text-ink">Invited suppliers</p>{rfq.suppliers.map((entry) => <div key={entry.id} className="mt-2 flex items-center justify-between text-xs"><Link href={`/dashboard/procurement/suppliers/${entry.supplier.id}`} className="text-ink hover:text-gold">{entry.supplier.name}</Link><Badge status={entry.status}>{entry.status.replaceAll("_", " ")}</Badge></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Commercial comparison</CardTitle><span className="text-xs text-ink-faint">Normalized in source currency</span></CardHeader><CardContent className="p-0 pt-4"><Table><THead><TRow><TH>Supplier</TH><TH>Reference</TH><TH>Offer</TH><TH>Lead time</TH><TH>Technical</TH><TH>Validity</TH></TRow></THead><TBody>{rfq.quotations.map((quote) => <TRow key={quote.id}><TD className="font-medium text-ink">{quote.supplier.name}{quote.total === lowest && <span className="ml-2 inline-flex items-center gap-1 rounded-full bg-success-soft px-2 py-0.5 text-[0.62rem] text-success"><CheckCircle2 size={10} />Lowest</span>}</TD><TD className="text-ink-muted">{quote.supplierReference ?? quote.number}</TD><TD><p className="inline-flex items-center gap-1 font-semibold text-ink"><CircleDollarSign size={12} />{formatCurrency(quote.total, quote.currency)}</p><p className="text-[0.65rem] text-ink-faint">Base {formatCurrency(quote.subtotal, quote.currency)}</p></TD><TD className="text-ink-muted">{quote.leadTimeDays ? `${quote.leadTimeDays} days` : "—"}</TD><TD><Badge status={quote.technicalStatus}>{quote.technicalStatus}</Badge></TD><TD className="text-ink-muted">{quote.validityDate ? formatDate(quote.validityDate) : "—"}</TD></TRow>)}{!rfq.quotations.length && <TRow><TD colSpan={6} className="py-12 text-center text-ink-faint">Record supplier quotations to build the comparison.</TD></TRow>}</TBody></Table></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Activity and issue history</CardTitle></CardHeader><CardContent>{activity.length ? <ul className="space-y-3">{activity.map((event) => <li key={event.id} className="flex gap-3"><span className="mt-1.5 h-2 w-2 rounded-full bg-gold" /><div><p className="text-sm text-ink">{event.summary}</p><p className="text-[0.68rem] text-ink-faint">{event.actor.displayName} · {formatDate(event.createdAt)}</p></div></li>)}</ul> : <p className="text-sm text-ink-faint">No activity.</p>}</CardContent></Card>
  </div>;
}
