import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, CalendarDays, MapPin } from "lucide-react";
import { getCurrentUser } from "@/lib/dal";
import { can } from "@/lib/permissions";
import { getPurchaseOrder, listProcurementActivity } from "@/server/procurement";
import { ProcurementNav } from "@/components/procurement/procurement-nav";
import { ProcurementStatusControl } from "@/components/procurement/procurement-status-control";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TBody, TD, TH, THead, TRow } from "@/components/ui/table";
import { formatDate } from "@/lib/utils";
import { getConfigResolver } from "@/server/platform-config";
import { formatMinor } from "@/lib/money";

export default async function PurchaseOrderPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { tenantId, role, company } = await getCurrentUser();
  if (!can(role, "PROCUREMENT", "READ")) redirect("/dashboard/executive");
  if (!(await getConfigResolver(tenantId, company?.id))("procurement.page.orders")) redirect("/dashboard/procurement");
  const [order, activity] = await Promise.all([getPurchaseOrder(tenantId, id), listProcurementActivity(tenantId, "PURCHASE_ORDER", id)]);
  const canWrite = can(role, "PROCUREMENT", "WRITE");
  return <div className="space-y-6"><Link href="/dashboard/procurement/orders" className="inline-flex items-center gap-1.5 text-sm text-ink-muted"><ArrowLeft size={14} /> Purchase orders</Link><div className="flex flex-col gap-4 rounded-2xl border border-border bg-surface p-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-gold">{order.number}</span><Badge status={order.status}>{order.status.replaceAll("_", " ")}</Badge><span className="text-xs text-ink-faint">Version {order.version}</span></div><h1 className="mt-2 text-2xl font-semibold text-ink">{order.title ?? order.description}</h1><p className="mt-2 text-sm text-ink-muted">Supplier: <Link href={`/dashboard/procurement/suppliers/${order.supplier.id}`} className="font-medium text-ink hover:text-gold">{order.supplier.name}</Link></p><div className="mt-4 flex flex-wrap gap-4 text-xs text-ink-muted"><span>{order.project?.name ?? "Company-wide"}</span>{order.requestedDeliveryDate && <span className="inline-flex items-center gap-1"><CalendarDays size={12} />Requested {formatDate(order.requestedDeliveryDate)}</span>}{order.deliveryAddress && <span className="inline-flex items-center gap-1"><MapPin size={12} />{order.deliveryAddress}</span>}</div></div>{canWrite && <ProcurementStatusControl entity="order" id={order.id} status={order.status} />}</div><ProcurementNav active="orders" />
    <div className="grid gap-4 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><CardTitle>Order lines</CardTitle></CardHeader><CardContent className="p-0 pt-4"><Table><THead><TRow><TH>#</TH><TH>Description</TH><TH>Quantity</TH><TH>Unit price</TH><TH>Delivered</TH><TH>Line total</TH></TRow></THead><TBody>{order.lines.map((line) => <TRow key={line.id}><TD>{line.lineNumber}</TD><TD className="font-medium text-ink">{line.description}<p className="text-[0.68rem] font-normal text-ink-faint">{line.lineType}</p></TD><TD>{line.quantity} {line.unit}</TD><TD>{formatMinor(line.unitPriceMinor, order.currency)}</TD><TD>{line.deliveredQuantity} / {line.quantity}</TD><TD className="font-medium text-ink">{formatMinor(line.lineTotalMinor, order.currency)}</TD></TRow>)}{!order.lines.length && <TRow><TD colSpan={6} className="py-8 text-center text-ink-muted">Legacy order scope: {order.description}</TD></TRow>}</TBody></Table></CardContent></Card><Card><CardHeader><CardTitle>Commercial control</CardTitle></CardHeader><CardContent className="space-y-3"><Row label="Subtotal" value={formatMinor(order.subtotalMinor || order.amountMinor, order.currency)} /><Row label="Discount" value={formatMinor(order.discountMinor, order.currency)} /><Row label="Tax" value={formatMinor(order.taxMinor, order.currency)} /><Row label="Freight" value={formatMinor(order.freightMinor, order.currency)} /><div className="border-t border-border pt-3"><Row label="Order total" value={formatMinor(order.amountMinor, order.currency)} /></div><Row label="Payment terms" value={order.paymentTerms ?? "—"} /><Row label="Supplier reference" value={order.supplierReference ?? "—"} /><Row label="Issued" value={order.issueDate ? formatDate(order.issueDate) : "Not issued"} /><Row label="Acknowledged" value={order.acknowledgedAt ? formatDate(order.acknowledgedAt) : "Pending"} /></CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Deliveries</CardTitle></CardHeader><CardContent>{order.deliveries.length ? <ul className="divide-y divide-border">{order.deliveries.map((delivery) => <li key={delivery.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-medium text-ink">{delivery.number}</p><p className="text-xs text-ink-faint">{delivery.expectedAt ? formatDate(delivery.expectedAt) : "Date pending"}</p></div><Badge status={delivery.status}>{delivery.status.replaceAll("_", " ")}</Badge></li>)}</ul> : <p className="py-6 text-center text-sm text-ink-faint">No delivery schedules.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Immutable history</CardTitle></CardHeader><CardContent>{activity.length ? <ul className="space-y-3">{activity.map((event) => <li key={event.id} className="flex gap-3"><span className="mt-1.5 h-2 w-2 rounded-full bg-gold" /><div><p className="text-sm text-ink">{event.summary}</p><p className="text-[0.68rem] text-ink-faint">{event.actor.displayName} · {formatDate(event.createdAt)}</p></div></li>)}</ul> : <p className="text-sm text-ink-faint">No activity.</p>}</CardContent></Card></div>
  </div>;
}
function Row({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex items-center justify-between gap-3 text-sm"><span className="text-ink-muted">{label}</span><span className="text-right font-medium text-ink">{value}</span></div>; }
