"use server";

import { z } from "zod";
import { revalidatePath } from "next/cache";
import { getCurrentUser } from "@/lib/dal";
import { can } from "@/lib/permissions";
import { assertConfigEnabled } from "@/server/platform-config";
import { createConstraint, createDailyReport, createDelay, createWorkPackage, recordProgress, submitDailyReport, transitionWorkPackage } from "@/server/work-progress";

export type WorkProgressActionState = { error?: string; success?: string } | undefined;
const errorState = (e: unknown, fallback: string) => ({ error: e instanceof Error ? e.message : fallback });
async function context(key?: string) { const c = await getCurrentUser(); if (!can(c.role, "PROJECTS", "WRITE")) throw new Error("You do not have permission to manage work progress."); if (key) await assertConfigEnabled(c.tenantId, key, c.company?.id); if (!c.company) throw new Error("A company workspace is required."); return c; }
const optionalDate = z.preprocess(v => v ? new Date(String(v)) : undefined, z.date().optional());

export async function createWorkPackageAction(_: WorkProgressActionState, formData: FormData): Promise<WorkProgressActionState> { try { const c = await context("work_progress.action.create_package"); const p = z.object({ projectId: z.string().min(1), name: z.string().min(2), description: z.string().optional(), discipline: z.string().min(2), location: z.string().optional(), contractorName: z.string().optional(), measurementMethod: z.string().min(1), unit: z.string().min(1), approvedQuantity: z.coerce.number().positive(), weight: z.coerce.number().min(0).optional(), plannedStart: optionalDate, plannedFinish: optionalDate }).safeParse(Object.fromEntries(formData)); if (!p.success) return { error: p.error.issues[0]?.message ?? "Invalid package" }; await createWorkPackage(c.tenantId, c.user.id, { companyId: c.company.id, ...p.data }); revalidatePath("/dashboard/work-progress"); return { success: "Work package created." }; } catch(e) { return errorState(e, "Could not create work package."); } }

export async function recordProgressAction(_: WorkProgressActionState, formData: FormData): Promise<WorkProgressActionState> { try { const c = await context("work_progress.action.capture_progress"); const p = z.object({ workPackageId: z.string().min(1), quantity: z.coerce.number().positive(), effectiveAt: z.coerce.date(), location: z.string().optional(), notes: z.string().optional(), idempotencyKey: z.string().min(8) }).safeParse(Object.fromEntries(formData)); if (!p.success) return { error: p.error.issues[0]?.message ?? "Invalid progress update" }; await recordProgress(c.tenantId, c.user.id, p.data); revalidatePath("/dashboard/work-progress"); revalidatePath(`/dashboard/work-progress/packages/${p.data.workPackageId}`); return { success: "Progress accepted and rollups recalculated." }; } catch(e) { return errorState(e, "Could not record progress."); } }

export async function createDailyReportAction(_: WorkProgressActionState, formData: FormData): Promise<WorkProgressActionState> { try { const c = await context("work_progress.action.create_daily_report"); const p = z.object({ projectId: z.string().min(1), reportDate: z.coerce.date(), shift: z.string().min(1), weather: z.string().optional(), siteConditions: z.string().optional(), workforceJson: z.string().optional(), equipmentJson: z.string().optional(), workCompleted: z.string().optional(), deliveriesJson: z.string().optional(), issues: z.string().optional(), qualityNotes: z.string().optional(), hseNotes: z.string().optional(), nextShiftPlan: z.string().optional() }).safeParse(Object.fromEntries(formData)); if (!p.success) return { error: p.error.issues[0]?.message ?? "Invalid daily report" }; await createDailyReport(c.tenantId, c.user.id, { companyId: c.company.id, ...p.data }); revalidatePath("/dashboard/work-progress/daily-reports"); return { success: "Daily site report saved as draft." }; } catch(e) { return errorState(e, "Could not create daily report."); } }

export async function createConstraintAction(_: WorkProgressActionState, formData: FormData): Promise<WorkProgressActionState> { try { const c = await context("work_progress.action.create_constraint"); const p = z.object({ projectId: z.string().min(1), workPackageId: z.string().optional(), title: z.string().min(2), category: z.string().min(1), description: z.string().optional(), impact: z.string().min(1), requiredBy: optionalDate }).safeParse(Object.fromEntries(formData)); if (!p.success) return { error: p.error.issues[0]?.message ?? "Invalid constraint" }; await createConstraint(c.tenantId, c.user.id, { companyId: c.company.id, ...p.data, workPackageId: p.data.workPackageId || undefined }); revalidatePath("/dashboard/work-progress/control"); return { success: "Constraint recorded." }; } catch(e) { return errorState(e, "Could not create constraint."); } }

export async function createDelayAction(_: WorkProgressActionState, formData: FormData): Promise<WorkProgressActionState> { try { const c = await context("work_progress.action.create_delay"); const p = z.object({ projectId: z.string().min(1), workPackageId: z.string().optional(), title: z.string().min(2), category: z.string().min(1), observedFact: z.string().min(2), allegedResponsibility: z.string().optional(), startAt: z.coerce.date(), impactDays: z.coerce.number().min(0).optional(), mitigation: z.string().optional() }).safeParse(Object.fromEntries(formData)); if (!p.success) return { error: p.error.issues[0]?.message ?? "Invalid delay" }; await createDelay(c.tenantId, c.user.id, { companyId: c.company.id, ...p.data, workPackageId: p.data.workPackageId || undefined }); revalidatePath("/dashboard/work-progress/control"); return { success: "Delay event recorded." }; } catch(e) { return errorState(e, "Could not record delay."); } }

export async function transitionWorkPackageAction(id: string, status: string) { const c = await context(); await transitionWorkPackage(c.tenantId, c.user.id, id, status); revalidatePath("/dashboard/work-progress"); }
export async function submitDailyReportAction(id: string) { const c = await context(); await submitDailyReport(c.tenantId, c.user.id, id); revalidatePath("/dashboard/work-progress/daily-reports"); }
