import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Building2, Mail, Phone, ShieldCheck, TriangleAlert } from "lucide-react";
import { getCurrentUser } from "@/lib/dal";
import { can } from "@/lib/permissions";
import { getSupplier, listProcurementActivity } from "@/server/procurement";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { formatCurrency, formatDate } from "@/lib/utils";
import { ProcurementNav } from "@/components/procurement/procurement-nav";
import { getConfigResolver } from "@/server/platform-config";
import { AddSupplierQualificationDialog } from "@/components/procurement/procurement-dialogs";
import { SupplierStatusControl } from "@/components/procurement/procurement-status-control";

export default async function SupplierPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { tenantId, role, company } = await getCurrentUser();
  if (!can(role, "PROCUREMENT", "READ")) redirect("/dashboard/executive");
  if (!(await getConfigResolver(tenantId, company?.id))("procurement.page.suppliers")) redirect("/dashboard/procurement");
  const [supplier, activity] = await Promise.all([getSupplier(tenantId, id), listProcurementActivity(tenantId, "SUPPLIER", id)]);
  const committed = supplier.purchaseOrders.filter((o) => !["DRAFT", "CANCELLED"].includes(o.status)).reduce((sum, o) => sum + o.amount, 0);
  const canWrite = can(role, "PROCUREMENT", "WRITE");
  return <div className="space-y-6">
    <Link href="/dashboard/procurement/suppliers" className="inline-flex items-center gap-1.5 text-sm text-ink-muted hover:text-ink"><ArrowLeft size={14} /> Supplier directory</Link>
    <div className="flex flex-col gap-4 rounded-2xl border border-border bg-surface p-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gold-soft text-gold"><Building2 size={22} /></div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-xl font-semibold text-ink">{supplier.tradingName ?? supplier.name}</h1><Badge status={supplier.status}>{supplier.status.replaceAll("_", " ")}</Badge></div><p className="mt-1 text-sm text-ink-muted">{supplier.number} · {supplier.legalName ?? supplier.name} · {supplier.category}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-ink-muted">{supplier.email && <span className="inline-flex items-center gap-1"><Mail size={12} />{supplier.email}</span>}{supplier.phone && <span className="inline-flex items-center gap-1"><Phone size={12} />{supplier.phone}</span>}<span>{supplier.countryCode}</span></div></div></div><div className="flex flex-col items-start gap-2 sm:items-end"><div className="text-left sm:text-right"><p className="text-[0.65rem] uppercase tracking-wide text-ink-faint">Overall score</p><p className="text-2xl font-semibold text-ink">{supplier.overallScore?.toFixed(0) ?? "—"}<span className="text-xs font-normal text-ink-faint"> / 100</span></p></div>{canWrite && <div className="flex gap-2"><AddSupplierQualificationDialog supplierId={supplier.id} /><SupplierStatusControl id={supplier.id} status={supplier.status} /></div>}</div></div>
    <ProcurementNav active="suppliers" />
    <div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle>Qualification</CardTitle></CardHeader><CardContent><p className="text-lg font-semibold text-ink">{supplier.qualificationStatus.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-ink-muted">{supplier.qualifications[0]?.validUntil ? `Valid until ${formatDate(supplier.qualifications[0].validUntil)}` : "No active validity date"}</p><div className="mt-4 space-y-2">{supplier.qualifications.slice(0, 3).map((q) => <div key={q.id} className="rounded-lg bg-surface-sunken p-2 text-xs"><strong className="text-ink">{q.outcome.replaceAll("_", " ")}</strong>{q.score !== null && <span className="float-right text-ink-muted">{q.score}/100</span>}<p className="mt-1 text-ink-faint">{formatDate(q.createdAt)}</p></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Commercial summary</CardTitle></CardHeader><CardContent className="space-y-3"><Row label="Committed value" value={formatCurrency(committed, supplier.currency)} /><Row label="Purchase orders" value={supplier.purchaseOrders.length} /><Row label="Quotation history" value={supplier.quotations.length} /><Row label="Lead time" value={supplier.leadTimeDays ? `${supplier.leadTimeDays} days` : "—"} /><Row label="Payment terms" value={supplier.paymentTerms ?? "—"} /></CardContent></Card><Card><CardHeader><CardTitle>Risk</CardTitle></CardHeader><CardContent>{supplier.riskFlags.length ? <div className="space-y-2">{supplier.riskFlags.map((risk) => <div key={risk.id} className="rounded-lg border border-warning/20 bg-warning-soft p-3"><p className="flex items-center gap-1.5 text-xs font-semibold text-warning"><TriangleAlert size={13} />{risk.type.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-ink-muted">{risk.summary}</p></div>)}</div> : <div className="flex flex-col items-center py-5 text-center"><ShieldCheck className="text-success" /><p className="mt-2 text-sm font-medium text-ink">No open risk flags</p></div>}</CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Purchase history</CardTitle></CardHeader><CardContent>{supplier.purchaseOrders.length ? <ul className="divide-y divide-border">{supplier.purchaseOrders.map((o) => <li key={o.id} className="flex items-center justify-between gap-3 py-3"><div><Link href={`/dashboard/procurement/orders/${o.id}`} className="text-sm font-medium text-ink hover:text-gold">{o.number}</Link><p className="text-xs text-ink-faint">{o.project?.name ?? "Company-wide"}</p></div><div className="text-right"><p className="text-sm font-medium text-ink">{formatCurrency(o.amount, o.currency)}</p><Badge status={o.status}>{o.status.replaceAll("_", " ")}</Badge></div></li>)}</ul> : <p className="py-6 text-center text-sm text-ink-faint">No purchase orders.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Activity timeline</CardTitle></CardHeader><CardContent>{activity.length ? <ul className="space-y-4">{activity.map((event) => <li key={event.id} className="flex gap-3"><span className="mt-1.5 h-2 w-2 rounded-full bg-gold" /><div><p className="text-sm text-ink">{event.summary}</p><p className="text-[0.68rem] text-ink-faint">{event.actor.displayName} · {formatDate(event.createdAt)}</p></div></li>)}</ul> : <p className="py-6 text-center text-sm text-ink-faint">No activity yet.</p>}</CardContent></Card></div>
  </div>;
}

function Row({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex items-center justify-between gap-3 text-sm"><span className="text-ink-muted">{label}</span><span className="font-medium text-ink">{value}</span></div>; }
