"use client";
import { useActionState, useState, type ReactNode } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Plus, X } from "lucide-react";
import { activateBaselineAction, createConstraintAction, createDailyReportAction, createDelayAction, createEvidenceAction, createProgressDraftAction, createScheduleActivityAction, createScheduleVersionAction, createWorkPackageAction, recordProgressAction, submitProgressUpdateAction, verifyProgressUpdateAction, type WorkProgressActionState } from "@/app/actions/work-progress";
import { Button } from "@/components/ui/button"; import { Input, Label } from "@/components/ui/input";
type Action=(s:WorkProgressActionState,f:FormData)=>Promise<WorkProgressActionState>; type Picker={id:string;name:string};
function Field({label,name,children}:{label:string;name:string;children?:ReactNode}){return <div className="space-y-1.5"><Label htmlFor={name}>{label}</Label>{children??<Input id={name} name={name} required/>}</div>};
function Select({name,children,required=true,defaultValue=""}:{name:string;children:ReactNode;required?:boolean;defaultValue?:string}){return <select id={name} name={name} required={required} defaultValue={defaultValue} className="h-10 w-full rounded-lg border border-border bg-surface px-3 text-sm">{children}</select>};
function Box({title,trigger,action,children}:{title:string;trigger:string;action:Action;children:ReactNode}){const[open,setOpen]=useState(false);const[state,formAction,pending]=useActionState(action,undefined);return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><Button size="sm"><Plus size={14}/>{trigger}</Button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-ink/40"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[94vw] max-w-2xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-2xl border border-border bg-surface p-6 shadow-xl"><div className="mb-4 flex justify-between"><Dialog.Title className="font-semibold text-ink">{title}</Dialog.Title><Dialog.Close><X size={18}/></Dialog.Close></div><form action={formAction} className="space-y-3">{children}{state?.error&&<p className="rounded-lg bg-danger-soft p-2 text-xs text-danger">{state.error}</p>}{state?.success&&<p className="rounded-lg bg-success-soft p-2 text-xs text-success">{state.success}</p>}<Button className="w-full" disabled={pending}>{pending?"Saving…":"Save"}</Button></form></Dialog.Content></Dialog.Portal></Dialog.Root>}
const Project=({projects}:{projects:Picker[]})=><Field label="Project" name="projectId"><Select name="projectId"><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field>;
export function CreateWorkPackageDialog({projects}:{projects:Picker[]}){return <Box title="Create work package" trigger="New package" action={createWorkPackageAction}><div className="grid gap-3 sm:grid-cols-2"><Project projects={projects}/><Field label="Package name" name="name"/><Field label="Discipline" name="discipline"/><Field label="Location" name="location"><Input id="location" name="location"/></Field><Field label="Contractor" name="contractorName"><Input id="contractorName" name="contractorName"/></Field><Field label="Measurement method" name="measurementMethod"><Select name="measurementMethod" defaultValue="INSTALLED_QUANTITY"><option>INSTALLED_QUANTITY</option><option>COMPLETED_UNITS</option><option>WEIGHTED_MILESTONE</option><option>ACTIVITY_WEIGHTED</option><option>MANUAL</option><option>COMPOSITE</option></Select></Field><Field label="Approved quantity" name="approvedQuantity"><Input id="approvedQuantity" name="approvedQuantity" type="number" step="any" min="0.0001" required/></Field><Field label="Unit" name="unit"/><Field label="Weight" name="weight"><Input id="weight" name="weight" type="number" step="any" min="0" defaultValue="1"/></Field><Field label="Planned start" name="plannedStart"><Input id="plannedStart" name="plannedStart" type="date"/></Field><Field label="Planned finish" name="plannedFinish"><Input id="plannedFinish" name="plannedFinish" type="date"/></Field></div><Field label="Scope description" name="description"><textarea id="description" name="description" rows={3} className="w-full rounded-lg border border-border p-2"/></Field></Box>}
export function RecordProgressDialog({packages}:{packages:{id:string;name:string;code:string}[]}){return <Box title="Quick progress capture" trigger="Capture progress" action={recordProgressAction}><Field label="Work package" name="workPackageId"><Select name="workPackageId"><option value="">Select package</option>{packages.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Completed quantity" name="quantity"><Input id="quantity" name="quantity" type="number" min="0.0001" step="any"/></Field><Field label="Effective date" name="effectiveAt"><Input id="effectiveAt" name="effectiveAt" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><Field label="Location" name="location"><Input id="location" name="location"/></Field><Field label="Offline/idempotency key" name="idempotencyKey"><Input id="idempotencyKey" name="idempotencyKey" defaultValue={crypto.randomUUID()}/></Field></div><Field label="Notes" name="notes"><textarea id="notes" name="notes" rows={2} className="w-full rounded-lg border border-border p-2"/></Field></Box>}
export function CreateDailyReportDialog({projects}:{projects:Picker[]}){return <Box title="New daily site report" trigger="New report" action={createDailyReportAction}><div className="grid gap-3 sm:grid-cols-2"><Project projects={projects}/><Field label="Report date" name="reportDate"><Input id="reportDate" name="reportDate" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><Field label="Shift" name="shift"><Select name="shift" defaultValue="DAY"><option>DAY</option><option>NIGHT</option><option>SHIFT_1</option><option>SHIFT_2</option></Select></Field><Field label="Weather" name="weather"><Input id="weather" name="weather"/></Field></div>{[["Site conditions","siteConditions"],["Workforce and hours","workforceJson"],["Equipment and downtime","equipmentJson"],["Work completed","workCompleted"],["Deliveries/materials","deliveriesJson"],["Issues and constraints","issues"],["Quality notes","qualityNotes"],["HSE notes","hseNotes"],["Tomorrow / next shift","nextShiftPlan"]].map(([l,n])=><Field key={n} label={l} name={n}><textarea id={n} name={n} rows={2} className="w-full rounded-lg border border-border p-2"/></Field>)}</Box>}
export function CreateConstraintDialog({projects,packages}:{projects:Picker[];packages:{id:string;name:string}[]}){return <Box title="Record constraint" trigger="New constraint" action={createConstraintAction}><Project projects={projects}/><Field label="Affected package" name="workPackageId"><Select name="workPackageId" required={false}><option value="">Project-wide</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Title" name="title"/><Field label="Category" name="category"/><Field label="Impact" name="impact"/><Field label="Required by" name="requiredBy"><Input id="requiredBy" name="requiredBy" type="date"/></Field></div><Field label="Description" name="description"><textarea id="description" name="description" rows={2} className="w-full rounded-lg border border-border p-2"/></Field></Box>}
export function CreateDelayDialog({projects,packages}:{projects:Picker[];packages:{id:string;name:string}[]}){return <Box title="Record delay event" trigger="New delay" action={createDelayAction}><Project projects={projects}/><Field label="Affected package" name="workPackageId"><Select name="workPackageId" required={false}><option value="">Project-wide</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Title" name="title"/><Field label="Category" name="category"/><Field label="Start date" name="startAt"><Input id="startAt" name="startAt" type="date"/></Field><Field label="Impact days" name="impactDays"><Input id="impactDays" name="impactDays" type="number" min="0" step="any"/></Field></div><Field label="Observed fact" name="observedFact"><textarea id="observedFact" name="observedFact" rows={2} className="w-full rounded-lg border border-border p-2"/></Field><Field label="Alleged responsibility (kept separate)" name="allegedResponsibility"><Input id="allegedResponsibility" name="allegedResponsibility"/></Field><Field label="Mitigation" name="mitigation"><textarea id="mitigation" name="mitigation" rows={2} className="w-full rounded-lg border border-border p-2"/></Field></Box>}

export function CreateScheduleVersionDialog({projects}:{projects:Picker[]}){return <Box title="New working schedule version" trigger="New schedule version" action={createScheduleVersionAction}><Project projects={projects}/><div className="grid gap-3 sm:grid-cols-2"><Field label="Version name" name="name"/><Field label="Data date" name="dataDate"><Input id="dataDate" name="dataDate" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field></div></Box>}

export function CreateScheduleActivityDialog({versions,packages}:{versions:Picker[];packages:{id:string;name:string}[]}){return <Box title="Add schedule activity" trigger="New activity" action={createScheduleActivityAction}><Field label="Schedule version" name="scheduleVersionId"><Select name="scheduleVersionId"><option value="">Select version</option>{versions.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</Select></Field><Field label="Linked package" name="workPackageId"><Select name="workPackageId" required={false}><option value="">Unmapped</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Activity code" name="code"/><Field label="Activity name" name="name"/><Field label="Planned start" name="plannedStart"><Input id="plannedStart" name="plannedStart" type="date"/></Field><Field label="Planned finish" name="plannedFinish"><Input id="plannedFinish" name="plannedFinish" type="date"/></Field><Field label="Predecessor code" name="predecessorCode"><Input id="predecessorCode" name="predecessorCode"/></Field><Field label="Lag days" name="lagDays"><Input id="lagDays" name="lagDays" type="number" defaultValue="0"/></Field></div></Box>}

export function ActivateBaselineButton({scheduleVersionId,disabled}:{scheduleVersionId:string;disabled?:boolean}){const[pending,setPending]=useState(false);return <Button size="sm" variant="secondary" disabled={disabled||pending} onClick={async()=>{setPending(true);try{await activateBaselineAction(scheduleVersionId)}finally{setPending(false)}}}>{pending?"Activating…":"Activate as baseline"}</Button>}

export function CreateEvidenceDialog({projects,packages}:{projects:Picker[];packages:{id:string;name:string}[]}){return <Box title="Log progress evidence" trigger="Log evidence" action={createEvidenceAction}><Project projects={projects}/><Field label="Linked package" name="workPackageId"><Select name="workPackageId" required={false}><option value="">Project-wide</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Title" name="title"/><Field label="Type" name="type"><Select name="type" required={false} defaultValue="PHOTO"><option>PHOTO</option><option>VIDEO</option><option>DOCUMENT</option><option>THREE_SIXTY</option></Select></Field><Field label="Captured at" name="capturedAt"><Input id="capturedAt" name="capturedAt" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><Field label="Location" name="location"><Input id="location" name="location" required={false}/></Field></div><Field label="File / reference URL" name="url"><Input id="url" name="url" required={false}/></Field></Box>}

export function CreateProgressClaimDialog({packages}:{packages:{id:string;name:string;code:string}[]}){return <Box title="Draft progress claim for verification" trigger="Draft claim" action={createProgressDraftAction}><Field label="Work package" name="workPackageId"><Select name="workPackageId"><option value="">Select package</option>{packages.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Claimed quantity" name="quantity"><Input id="quantity" name="quantity" type="number" min="0.0001" step="any"/></Field><Field label="Effective date" name="effectiveAt"><Input id="effectiveAt" name="effectiveAt" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><Field label="Location" name="location"><Input id="location" name="location"/></Field><Field label="Offline/idempotency key" name="idempotencyKey"><Input id="idempotencyKey" name="idempotencyKey" defaultValue={crypto.randomUUID()}/></Field></div><Field label="Notes" name="notes"><textarea id="notes" name="notes" rows={2} className="w-full rounded-lg border border-border p-2"/></Field></Box>}

export function ProgressWorkflowActions({id,workPackageId,status}:{id:string;workPackageId:string;status:string}){
  const[pending,setPending]=useState(false);
  const run=async(fn:()=>Promise<void>)=>{setPending(true);try{await fn()}finally{setPending(false)}};
  if(status==="DRAFT")return <Button size="sm" disabled={pending} onClick={()=>run(()=>submitProgressUpdateAction(id,workPackageId))}>{pending?"Submitting…":"Submit for verification"}</Button>;
  if(status==="SUBMITTED"||status==="UNDER_VERIFICATION")return <div className="flex gap-2"><Button size="sm" disabled={pending} onClick={()=>run(()=>verifyProgressUpdateAction(id,workPackageId,"ACCEPTED"))}>{pending?"Verifying…":"Accept"}</Button><Button size="sm" variant="secondary" disabled={pending} onClick={()=>run(()=>verifyProgressUpdateAction(id,workPackageId,"REJECTED"))}>Reject</Button></div>;
  return null;
}
